#连接数据库
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.111.107.197:3306/erp?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      username: root
      password: dm123456789&M
      initialSize: 3
      minIdle: 3
      maxActive: 30
      maxWait: 15000
      validationQuery: SELECT 'x'
      #监控的配置
      stat-view-servlet:
        login-username: root
        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
        enabled: true
#配置thymeleaf
  thymeleaf:
    cache: false
    enabled: true
#mybaitsplus的配置
mybatis-plus:
  mapper-locations:
  - classpath:mapper/*/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    global-config:
      db-config:
        id-type: auto  #配置全局的ID自动增长
#shiro的配置
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  login-url: /index.html
  target-bean-name: shiroFilter
  target-filter-lifecycle: true
  unauthorized-url: /unauthorized.html
  anon-urls:
  - /login/login*
  - /index.html*
  - /login.html*
  - /resources/**
  authc-urls:
  - /**

